### ISSUE TITLE
Level Editor Bugs

### ISSUE THREAD

**Issue by Magirus-Deutz** [mmatyas/supermariowar#127]
1 - Limited to 128 folders
If you switch to tileset folder 129, the tileset can't processed.
2 - The tileset page in platform mode
If you open the platform mode, then can not open the tilesets page
(for example: https://youtu.be/n0Bo445W_9o)

**Comment by AzureBerylBlue** [comment]
I fixed pressing T and A, and the offset menu bugs in #128

**Comment by Magirus-Deutz** [comment]
and first bug example: https://youtu.be/th0On05iqOw

**Comment by AzureBerylBlue** [comment]
I think that's being caused by these lines:
https://github.com/mmatyas/supermariowar/blob/master/src/common/map.cpp#L975
https://github.com/mmatyas/supermariowar/blob/master/src/common/map.cpp#L1013
I don't think it's possible to have more than 128 tilesets in one map without changing the map format.

**Comment by mmatyas** [comment]
Yes, a map file can contain up to 128 tilesets. Each one of them can hold at most 128x128 tiles, giving you an upper limit of 2097152 possible tiles, which should be more than enough even if you cover the whole map with different tiles.

**Comment by Magirus-Deutz** [comment]
then, is that bug because of this?
https://youtu.be/mT1ft2eidqw (Tiles is limited to 32 block)

**Comment by mmatyas** [comment]
That does look like a bug, yes. (By the way, thanks for showing things with videos!)

**Comment by mmatyas** [comment]
Ok, this should be fixed now in the latest build!
