### ISSUE TITLE
Game crashes with bombs and flipblocks

### ISSUE THREAD

**Issue by AzureBerylBlue** [mmatyas/supermariowar#155]
I think bombs and flipblocks are crashing the game. If you leave the game running with AI players in this tour, the game will eventually crash.
[CrashTour.zip](https://github.com/mmatyas/supermariowar/files/4775371/CrashTour.zip)

**Comment by mmatyas** [comment]
Looks like this happens in certain cases when the player drops a carried item due to death. So far the game crashed for me at these locations:

- https://github.com/mmatyas/supermariowar/blob/40f7bd6edb44a177ab1ea6dbb3f1ef3c1fcc1325/src/smw/player.cpp#L1097
- https://github.com/mmatyas/supermariowar/blob/40f7bd6edb44a177ab1ea6dbb3f1ef3c1fcc1325/src/smw/player.cpp#L1645

It seems as if `carriedItem` points to some invalid memory, probably it's not properly set to null in one of the functions called during the gameplay.
