### ISSUE TITLE
Game won't luanch because of missing files

### ISSUE THREAD

**Issue by deoxal** [mmatyas/supermariowar#186]
When trying to launch the game I get this message

> ERROR: Empty directory.  data/gfx/packs/Classic/tilesets/
ERROR: Empty map directory!
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR: Empty map directory!
Aborted (core dumped)

I am running Linux Mint 20.1 if it matters

Any suggestions?

**Comment by mmatyas** [comment]
Hi, make sure you start the game from the directory of the executable, or call the program with the directory path as parameter.

**Comment by mmatyas** [comment]
Actually, I think this could be improved, let's see...

**Comment by deoxal** [comment]
Yes I did, I didn't move the executable or anything.

Previously it said I was missing libSDL_mixer but I was able to solve that by installing it from ubuntu.pkgs.org

**Comment by mmatyas** [comment]
Ok, just made [a new build](https://github.com/mmatyas/supermariowar/releases/download/continuous/supermariowar_2021-04-03_linux.zip), could you try it?

**Comment by deoxal** [comment]
Yes it works now, what did you do? Can I donate to you? I really appreciate the quick response and fix.

One other thing, I can only launch it from the terminal. Trying to launch it just by double clicking in the file manager doesn't work so I put the path in an executable file and use that to launch it. I think it's not being recognized because the file manager (Nemo) classifies it as **shared library (application/x-sharedlib)** whereas another app I installed outside the package manager is classified as **program (application/x-executable)**

**Comment by mmatyas** [comment]
Haha, thanks! The game didn't find the files because it was searching for them relative to the *current working directory*, not the game's location. Finding out where an executable is located is a surprisingly complex task, which is why it didn't work before, but with the SDL2 port done in the past years, this could also be done in a simpler way.

For some reason GitHub removed the executable bit from the binary, I'll see if I can fix that real quick.

**Comment by mmatyas** [comment]
Had to edit a few things but it should work now!
(Ah right, about donations, that's *completely* optional, but if you do wish for it, [I accept coffee here](https://www.buymeacoffee.com/mmatyas))

**Comment by deoxal** [comment]
No luck, all each of the files are listed as shared libraries.

**Comment by mmatyas** [comment]
Turns out this actually isn't a trivial thing on Linux -- it seems on Ubuntu/Debian based distros all binaries are marked as "shared object" by default. [Here are some technical details about why](https://stackoverflow.com/questions/41398444/gcc-creates-mime-type-application-x-sharedlib-instead-of-application-x-applicati/41398832#41398832) (in short, for security). If you take a look at `/usr/bin/`, for example, you'll also see most core programs are in fact shared objects too.

So whether one can run binaries by double clicking seems to depend on the file manager. I found [a bug report for Nemo](https://github.com/linuxmint/nemo/issues/2385), but if you have an option like this below, you might try turning it on:

![](https://i.stack.imgur.com/cEzAb.png)

If there's no such option, you could try creating a script for the game -- file managers seem to have no troubles launching that. You can create a text file with the following contents:

```sh
#! /bin/bash
./smw
```

, save it as `smw.sh` and mark *that* as executable (should work as described above this time).

**Comment by deoxal** [comment]
I do have the execute tick box like in your screenshot and checking it is how I was able to run it from the command line. Launching the game using an executable text file is what I have been doing and I'm happy with that.

**Comment by mmatyas** [comment]
I guess this can be closed.

**Comment by mamaaar** [comment]
same but I don't understand what I should do

moizaly@moizaly-Latitude-7490:~/Documents/githubprojects/supermariowar/build$ cmake ..
CMake Deprecation Warning at dependencies/enet/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at dependencies/enet/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

    SYSTEM:      Linux x86_64
    BUILD:       Release
    CC:          /usr/bin/cc
    CXX:         /usr/bin/c++
    C FLAGS:      -msse2 -O3 -s -Wall -Wextra -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -fno-strict-aliasing -fexceptions -Wno-shadow -fvisibility-inlines-hidden -fvisibility=hidden
    CXX FLAGS:    -msse2 -O3 -s -Wall -Wextra -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -fno-strict-aliasing -fexceptions -Wno-shadow -fvisibility-inlines-hidden -fvisibility=hidden
    LD FLAGS:    
    DEFINITIONS: NDEBUG
  [install]
    Binary dir:  /usr/local/games
    Data dir:    /usr/local/share/games/smw
    Docs dir:    /usr/local/share/doc/smw
-- Configuring done
-- Generating done
-- Build files have been written to: /home/moizaly/Documents/githubprojects/supermariowar/build
moizaly@moizaly-Latitude-7490:~/Documents/githubprojects/supermariowar/build$ make
Consolidate compiler generated dependencies of target enet
[  5%] Built target enet
Consolidate compiler generated dependencies of target yaml-cpp
[ 20%] Built target yaml-cpp
Consolidate compiler generated dependencies of target CommonFiles
[ 39%] Built target CommonFiles
Consolidate compiler generated dependencies of target NetplayFiles
[ 40%] Built target NetplayFiles
Consolidate compiler generated dependencies of target smw
[ 87%] Built target smw
Consolidate compiler generated dependencies of target smw-leveledit
[ 89%] Built target smw-leveledit
Consolidate compiler generated dependencies of target smw-worldedit
[ 96%] Built target smw-worldedit
Consolidate compiler generated dependencies of target smw-server
[100%] Built target smw-server
moizaly@moizaly-Latitude-7490:~/Documents/githubprojects/supermariowar/build$ ./smw
ERROR: Empty directory.  /home/moizaly/Documents/githubprojects/supermariowar/build/data/gfx/packs/Classic/tilesets/
ERROR: Empty map directory!

ERROR: Empty map directory!
moizaly@moizaly-Latitude-7490:~/Documents/githubprojects/supermariowar/build$
