### ISSUE TITLE
Publish on Flathub

### ISSUE THREAD

**Issue by Cwpute** [mmatyas/supermariowar#344]
Since there is a Flatpak available now, how would you feel about publishing the game to Flathub ? :)
https://docs.flathub.org/docs/for-app-authors/submission
It would definitely help revitalize this game and give it some visibility !

**Comment by mmatyas** [comment]
Hi! We have a custom Flatpak release because Flathub is more oriented towards "stable" releases, but we don't really have that yet. Unfortunately a continuously updated release would not be accepted there (I've run into a similar issue with one of my other projects). There's also some legal restrictions on the default assets, so a config file with some extra steps would be necessary.

**Comment by Cwpute** [comment]
thanks for your answer, here is hope a workable solution may be found someday :)
