### ISSUE TITLE
MSYS2 build instuctions for Windows not working

### ISSUE THREAD

**Issue by bgrimm** [mmatyas/supermariowar#69]
Current version of MSYS2 does not seem to work with build instructions:
https://github.com/mmatyas/supermariowar/wiki/Building-on-Windows

With installed dependencies and running cmake, errors out with missing libraries. (likely an issue with MSYS install).

Tested on Windows 7x64, MSYS_i686

**Comment by mmatyas** [comment]
Sorry for such a late reply, I couldn't test this last week, but I've managed to set up an MSYS2 build just now. Apparently `make` is no longer part of the MinGW toolchain package, which is why I get a message like this:

```sh
Win@Win-PC MINGW32 ~/supermariowar/build
$ cmake .. -G 'Unix Makefiles' -DUSE_SDL2_LIBS=1
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

This can be fixed by `pacman -S make`, then re-running CMake. The rest of the build should work fine.
